a = """<Coordinate x=3 y=3> 
<Coordinate x=2 y=2> 
<Coordinate x=3 y=2> 
<Coordinate x=4 y=2> 
<Coordinate x=2 y=3> 
<Coordinate x=4 y=3> 
<Coordinate x=2 y=4> 
<Coordinate x=3 y=4> 
<Coordinate x=4 y=4> 
<Coordinate x=2 y=1> 
<Coordinate x=3 y=1> 
<Coordinate x=4 y=1> 
<Coordinate x=2 y=2> 
<Coordinate x=5 y=1> 
<Coordinate x=5 y=2> 
<Coordinate x=5 y=3> 
<Coordinate x=1 y=2> 
<Coordinate x=1 y=3> 
<Coordinate x=1 y=4> 
<Coordinate x=2 y=4> 
<Coordinate x=5 y=4> 
<Coordinate x=2 y=3> 
<Coordinate x=1 y=5> 
<Coordinate x=2 y=5> 
<Coordinate x=3 y=5> 
<Coordinate x=4 y=5> 
<Coordinate x=5 y=5> 
<Coordinate x=2 y=0> 
<Coordinate x=3 y=0> 
<Coordinate x=4 y=0> 
<Coordinate x=5 y=0> 
<Coordinate x=6 y=0> 
<Coordinate x=6 y=1> 
<Coordinate x=6 y=2> 
<Coordinate x=6 y=3> 
<Coordinate x=6 y=4> 
<Coordinate x=0 y=2> 
<Coordinate x=1 y=2> 
<Coordinate x=0 y=3> 
<Coordinate x=0 y=4> 
<Coordinate x=1 y=4> 
<Coordinate x=1 y=3> 
<Coordinate x=0 y=5> 
<Coordinate x=1 y=5> 
<Coordinate x=2 y=5> 
<Coordinate x=2 y=3> 
<Coordinate x=6 y=5> 
<Coordinate x=2 y=2> 
<Coordinate x=2 y=4> 
<Coordinate x=0 y=6> 
<Coordinate x=1 y=6> 
<Coordinate x=2 y=6> 
<Coordinate x=3 y=6> 
<Coordinate x=4 y=6> 
<Coordinate x=5 y=6> 
<Coordinate x=6 y=6> 
<Coordinate x=2 y=0> 
<Coordinate x=4 y=0> 
<Coordinate x=2 y=1> 
<Coordinate x=3 y=0> 
<Coordinate x=7 y=0> 
<Coordinate x=7 y=1> 
<Coordinate x=7 y=2> 
<Coordinate x=7 y=3> 
<Coordinate x=7 y=4> 
<Coordinate x=7 y=5> 
<Coordinate x=0 y=2> 
<Coordinate x=0 y=4> 
<Coordinate x=0 y=3> 
<Coordinate x=0 y=5> 
<Coordinate x=2 y=3> 
<Coordinate x=2 y=2> 
<Coordinate x=0 y=6> 
<Coordinate x=7 y=6> 
<Coordinate x=0 y=7> 
<Coordinate x=1 y=7> 
<Coordinate x=2 y=7> 
<Coordinate x=3 y=7> 
<Coordinate x=4 y=7> 
<Coordinate x=5 y=7> 
<Coordinate x=6 y=7> 
<Coordinate x=7 y=7> 
<Coordinate x=3 y=0> 
<Coordinate x=2 y=0> 
<Coordinate x=2 y=1> 
<Coordinate x=3 y=1> 
<Coordinate x=4 y=1> 
<Coordinate x=8 y=0> 
<Coordinate x=8 y=1> 
<Coordinate x=8 y=2> 
<Coordinate x=8 y=3> 
<Coordinate x=8 y=4> 
<Coordinate x=8 y=5> 
<Coordinate x=8 y=6> 
<Coordinate x=3 y=2> 
<Coordinate x=3 y=3> 
<Coordinate x=3 y=4> 
<Coordinate x=8 y=7> 
<Coordinate x=0 y=8> 
<Coordinate x=1 y=8> 
<Coordinate x=2 y=8> 
<Coordinate x=3 y=6> 
<Coordinate x=3 y=7> 
<Coordinate x=3 y=8> 
<Coordinate x=4 y=6> 
<Coordinate x=4 y=7> 
<Coordinate x=4 y=8> 
<Coordinate x=5 y=8> 
<Coordinate x=6 y=8> 
<Coordinate x=7 y=8> 
<Coordinate x=8 y=8> 
<Coordinate x=3 y=0> 
<Coordinate x=4 y=2> 
<Coordinate x=9 y=0> 
<Coordinate x=9 y=1> 
<Coordinate x=9 y=2> 
<Coordinate x=9 y=3> 
<Coordinate x=9 y=4> 
<Coordinate x=9 y=5> 
<Coordinate x=9 y=6> 
<Coordinate x=9 y=7> 
<Coordinate x=4 y=3> 
<Coordinate x=4 y=4> 
<Coordinate x=3 y=5> 
<Coordinate x=4 y=5> 
<Coordinate x=9 y=8> 
<Coordinate x=0 y=9> 
<Coordinate x=1 y=9> 
<Coordinate x=2 y=9> 
<Coordinate x=3 y=9> 
<Coordinate x=4 y=9> 
<Coordinate x=5 y=9> 
<Coordinate x=6 y=9> 
<Coordinate x=7 y=9> 
<Coordinate x=8 y=9>""".split("\n")

from collections import Counter

print Counter(a)
